stages:
  - test
  - build


test:
  stage: test
  image: nixos/nix:latest
  before_script:
    - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
  script:
    - nix develop --command sbt stage


build-and-push:
  stage: build
  image: nixos/nix:latest
  variables:
    REGISTRY: "quay.io"
    IMAGE_NAME: "quay.io/org/repo"
    IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"
  before_script:
    - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
    - nix-env -iA nixpkgs.skopeo
    - echo "$QUAY_PASSWORD" | skopeo login -u "$QUAY_USERNAME" --pasword-stdin $REGISTRY
  script:
    - nix build .#container
    - skopeo copy "oci-archive:$(readlink result)" "docker://${IMAGE_NAME}:${IMAGE_TAG}"
    - skopeo copy "oci-archive:$(readlink result)" "docker://${IMAGE_NAME}:latest"