version = "3.11.1"

runner.dialect = scala3

maxColumn = 140

indent {
    main = 3
}

align {
    preset = more
}

assumeStandardLibraryStripMargin = true

rewrite {
    rules = [Imports, SortModifiers, PreferCurlyFors]

    scala3 {
        convertToNewSyntax = true
    }

    imports {
        sort = scalastyle
    }
}