rules = [
    RemoveUnused,
    RedundantSyntax,
    OrganizeImports,
    DisableSyntax,
    LeakingImplicitClassVal
]

RemoveUnused {
    imports = false
}

OrganizeImports {
    targetDialect = Scala3
    removeUnused = true
    groupedImports = AggressiveMerge
    groups = [
        "*",
        "skillstelem"
    ]
}

DisableSyntax {
    noVars = true
    noNulls = true
    noThrows = true
    noAsInstanceOf = true
}